version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./frontend/src:/app/src
    environment:
      SQLSERVER_CONNECTIONSTRING: "Server=sqlserver;Database=myapp;User=sa;Password=Password_123;MultipleActiveResultSets=true;"
    depends_on: 
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password_123"
      MSSQL_PID: "Express"
      

